### PR TITLE
Fix for issue #27

### PR DESCRIPTION
**Pull request by ethanbayliss**
Changing single quotes to double

### CODE REVIEW

**Comment by ethanbayliss** [comment]
#27 Template held incorrect quotes

**Comment by desimaniac** [comment]
It's already been fixed on the develop branch.

**Comment by ethanbayliss** [comment]
Nice work boss

**Comment by desimaniac** [comment]
No prob! :p

PS. We also tweaked the plex_autoscan_url.sh script.

**Comment by desimaniac** [comment]
And now merged to master.

**Pull request closed without merging**
